name: flutter_font_picker_fork_tony
description: A Flutter widget Fork that lets the user select a Google Font from a custom dropdown/screen.
version: 1.4.0
homepage: https://github.com/whiplashoo/flutter_font_picker

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.0.3

dev_dependencies:
  flutter_lints: ^2.0.1
  dart_code_metrics: ^4.15.2
  flutter_test:
    sdk: flutter
  args: ^2.4.0
  
flutter:


